import { Link } from "react-router-dom";
import { useAuth } from "../context/AuthContext";

const cats=[['Education','🎓','Scholarships, education loans and support'],['Agriculture','🌾','Farming, equipment and livelihood support'],['Business','▦','Loans, subsidies and entrepreneurship'],['Employment','◉','Jobs, skills and self-employment'],['Housing','⌂','Housing and basic infrastructure'],['Women & Child','♡','Women, children and family support'],['Healthcare','✚','Health and social protection'],['Social Welfare','◎','Inclusive welfare and assistance']];
export default function Home(){const {isAuthenticated}=useAuth(); return <main className="landing">
 <section className="hero container"><div className="hero-content"><div className="trust-pill"><span>●</span> AI-assisted • explainable • citizen-first</div><h1>Find government schemes that <em>fit your life.</em></h1><p>Tell Scheme Sahayak AI about your needs. We compare your profile with thousands of scheme records, explain why a scheme matches, help you plan finances and guide you to the official application channel.</p><div className="hero-actions"><Link className="btn btn-primary btn-large" to={isAuthenticated?'/profile':'/register'}>Find My Schemes <span>→</span></Link><Link className="btn btn-ghost btn-large" to="/schemes">Explore Schemes</Link></div><div className="trust-line"><span>✓ Personalized matching</span><span>✓ Transparent reasons</span><span>✓ Official-source guidance</span></div></div>
 <div className="hero-panel"><div className="hero-panel-top"><span>SCHEME SAHAYAK AI</span><span className="live-dot">● Live intelligence</span></div><div className="mock-profile"><div className="mock-avatar">S</div><div><b>Your scheme discovery profile</b><small>Purpose · Business expansion</small></div><span className="profile-score">92%</span></div><div className="match-card featured"><div className="match-label">BEST MATCH <span>92%</span></div><h3>Prime Minister's Employment Generation Programme</h3><p>Strong fit for your purpose, category and financial requirement.</p><div className="match-reasons"><span>✓ Purpose</span><span>✓ Category</span><span>✓ Finance</span></div></div><div className="mock-row"><div><b>4,693+</b><small>schemes indexed</small></div><div><b>AI</b><small>explainable matching</small></div><div><b>1 journey</b><small>discover → apply</small></div></div></div></section>
 <section className="proof-strip"><div className="container proof-grid"><div><strong>4,693+</strong><span>scheme records</span></div><div><strong>AI</strong><span>profile matching</span></div><div><strong>100%</strong><span>explainable results</span></div><div><strong>6</strong><span>Indian languages</span></div></div></section>
 <section className="section container"><div className="section-heading"><div><span className="eyebrow">ONE CLEAR JOURNEY</span><h2>From confusion to action</h2></div><p>No more searching through long government pages without knowing where you fit.</p></div><div className="journey-grid">{[['01','Build your profile','Share only the details needed to understand your scheme eligibility.'],['02','AI finds your matches','Our matching engine compares your profile with scheme criteria.'],['03','Understand the scheme','See benefits, eligibility, documents and why you matched.'],['04','Plan and apply','Estimate repayments, find nearby help and continue to the official portal.']].map(x=><div className="journey-card" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p><b>→</b></div>)}</div></section>
 <section className="section soft-section"><div className="container"><div className="section-heading"><div><span className="eyebrow">DISCOVER BY NEED</span><h2>Start with what matters to you</h2></div><Link to="/schemes" className="text-link">View all schemes →</Link></div><div className="category-grid">{cats.map(([name,icon,text])=><Link to={`/schemes?keyword=${encodeURIComponent(name)}`} className="category-card" key={name}><span className="category-icon">{icon}</span><div><h3>{name}</h3><p>{text}</p></div><span>→</span></Link>)}</div></div></section>
 <section className="section container"><div className="ai-banner"><div><span className="eyebrow">MEET YOUR ASSISTANT</span><h2>Ask Scheme Sahayak AI anything about schemes.</h2><p>Get plain-language guidance, discover relevant schemes and understand the next step without navigating alone.</p></div><Link className="btn btn-primary" to={isAuthenticated?'/recommendations':'/register'}>Start with AI matching →</Link></div></section>
 <footer className="footer"><div className="container footer-grid"><div><div className="brand footer-brand"><span className="brand-icon">✦</span><span><strong>Scheme Sahayak</strong><b> AI</b></span></div><p>AI-assisted discovery and guidance for Indian government schemes.</p></div><div><b>Explore</b><Link to="/how-it-works">How it works</Link><Link to="/schemes">Schemes</Link><Link to="/faq">FAQ</Link></div><div><b>Important</b><span>Verify eligibility with the implementing authority.</span><span>Scheme information should be checked against official sources.</span></div></div><div className="container footer-bottom">© 2026 Scheme Sahayak AI <span>•</span> AI-assisted guidance, not official approval.</div></footer>
 </main>}
